"""Type stubs for kaos_nlp_core._rust.algorithms."""

from typing import TypedDict

class DistanceResult(TypedDict):
    distance: float
    normalized: float
    similarity: float

def compare_batch(
    pairs: list[tuple[str, str]],
    algorithm: str = "jaro-winkler",
    n: int = 2,
    lowercase: bool = False,
    prefix_weight: float = 0.1,
) -> list[DistanceResult]: ...

# Edit distance
def levenshtein(a: str, b: str) -> DistanceResult: ...
def damerau_levenshtein(a: str, b: str) -> DistanceResult: ...
def osa(a: str, b: str) -> DistanceResult: ...
def hamming(a: str, b: str) -> DistanceResult: ...
def jaro(a: str, b: str) -> DistanceResult: ...
def jaro_winkler(a: str, b: str, prefix_weight: float = 0.1) -> DistanceResult: ...
def sorensen_dice(a: str, b: str) -> DistanceResult: ...

# Phonetic
def soundex_distance(a: str, b: str) -> DistanceResult: ...
def soundex_encode(a: str) -> str: ...
def metaphone_distance(a: str, b: str) -> DistanceResult: ...
def metaphone_encode(a: str) -> str: ...

# Sequence
def lcs_distance(a: str, b: str) -> DistanceResult: ...
def lcs_length(a: str, b: str) -> int: ...
def longest_common_substring(a: str, b: str) -> DistanceResult: ...
def longest_common_substring_length(a: str, b: str) -> int: ...

# Character n-gram
def ngram_jaccard(a: str, b: str, n: int = 2) -> DistanceResult: ...
def ngram_cosine(a: str, b: str, n: int = 2) -> DistanceResult: ...
def ngram_overlap(a: str, b: str, n: int = 2) -> DistanceResult: ...

# Token n-gram
def token_jaccard(a: str, b: str, lowercase: bool = False) -> DistanceResult: ...
def token_ngram_jaccard(a: str, b: str, n: int = 2, lowercase: bool = False) -> DistanceResult: ...
def token_ngram_cosine(a: str, b: str, n: int = 2, lowercase: bool = False) -> DistanceResult: ...
def token_ngram_overlap(a: str, b: str, n: int = 2, lowercase: bool = False) -> DistanceResult: ...
