"""Type stubs for kaos_nlp_core._rust.characters."""

def is_letter(ch: str) -> bool: ...
def is_number(ch: str) -> bool: ...
def is_punctuation(ch: str) -> bool: ...
def is_symbol(ch: str) -> bool: ...
def is_whitespace(ch: str) -> bool: ...
def is_uppercase(ch: str) -> bool: ...
def is_lowercase(ch: str) -> bool: ...
def is_terminal_punctuation(ch: str) -> bool: ...
def is_internal_punctuation(ch: str) -> bool: ...
def is_newline(ch: str) -> bool: ...
def is_dash(ch: str) -> bool: ...
