"""Type stubs for kaos_nlp_core._rust.hashing."""

class MinHashSignature:
    def jaccard(self, other: MinHashSignature) -> float: ...
    @property
    def values(self) -> list[int]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

class MinHasher:
    def __init__(self, num_perm: int = 128, seed: int = 42) -> None: ...
    def hash_set(self, items: list[str]) -> MinHashSignature: ...
    def hash_char_shingles(self, text: str, shingle_size: int) -> MinHashSignature: ...
    def hash_token_shingles(self, tokens: list[str], shingle_size: int) -> MinHashSignature: ...
    @property
    def num_perm(self) -> int: ...
    def __repr__(self) -> str: ...
    def __getnewargs__(self) -> tuple[int, int]: ...

class MinHashIndex:
    def __init__(self, bands: int = 1, rows: int = 1) -> None: ...
    @staticmethod
    def with_threshold(num_perm: int, threshold: float) -> MinHashIndex: ...
    @staticmethod
    def load(path: str) -> MinHashIndex: ...
    def insert(self, doc_id: int, signature: MinHashSignature) -> None: ...
    def query_candidates(self, signature: MinHashSignature) -> list[int]: ...
    def query_above_threshold(
        self, signature: MinHashSignature, threshold: float
    ) -> list[tuple[int, float]]: ...
    def get_signature(self, doc_id: int) -> MinHashSignature | None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def save(self, path: str) -> None: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

class DuplicateGroup:
    @property
    def canonical_id(self) -> int: ...
    @property
    def duplicates(self) -> list[tuple[int, float]]: ...
    def __repr__(self) -> str: ...

class CTPHDigest:
    def similarity(self, other: CTPHDigest) -> float: ...
    def piece_similarity(self, other: CTPHDigest) -> float: ...
    @property
    def num_pieces(self) -> int: ...
    @property
    def window_size(self) -> int: ...
    @property
    def digest_size(self) -> int: ...
    @property
    def blocks(self) -> list[str]: ...
    @staticmethod
    def from_string(s: str) -> CTPHDigest: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

class CTPH:
    def __init__(self, window_size: int = 64, digest_size: int = 8, precision: int = 4) -> None: ...
    def compute(self, data: bytes) -> CTPHDigest: ...
    def hash_str(self, text: str) -> CTPHDigest: ...
    def __repr__(self) -> str: ...
    def __getnewargs__(self) -> tuple[int, int, int]: ...

class TokenCTPH:
    def __init__(self, window_size: int = 4, digest_size: int = 8) -> None: ...
    def compute(self, tokens: list[int]) -> CTPHDigest: ...
    def __repr__(self) -> str: ...
    def __getnewargs__(self) -> tuple[int, int]: ...

def find_duplicates(
    hasher: MinHasher,
    documents: list[tuple[int, list[str]]],
    shingle_size: int = 2,
    threshold: float = 0.5,
) -> list[DuplicateGroup]: ...
def ctph_hash_bytes(
    data: bytes,
    window_size: int = 64,
    digest_size: int = 8,
    precision: int = 4,
) -> str: ...
def ctph_hash_str(
    text: str,
    window_size: int = 64,
    digest_size: int = 8,
    precision: int = 4,
) -> str: ...
def ctph_similarity(hash1: str, hash2: str) -> float: ...
def ctph_piece_similarity(hash1: str, hash2: str) -> float: ...
def token_ctph_hash(tokens: list[int], window_size: int = 4, digest_size: int = 8) -> str: ...
