"""Type stubs for kaos_nlp_core._rust.lexicon."""

from typing import Any

from kaos_nlp_core._rust.matching import FstSet

class Lexicon:
    def __init__(self) -> None: ...
    @staticmethod
    def load(path: str) -> Lexicon: ...
    @staticmethod
    def default_embedded() -> Lexicon: ...
    def add_entry(self, entry: dict[str, Any]) -> None: ...
    def add_entries(self, entries: list[dict[str, Any]]) -> None: ...
    def contains(self, word: str) -> bool: ...
    def synonyms(self, word: str) -> list[str]: ...
    def antonyms(self, word: str) -> list[str]: ...
    def hypernyms(self, word: str) -> list[str]: ...
    def hyponyms(self, word: str) -> list[str]: ...
    def inflections(self, word: str) -> list[str]: ...
    def collocations(self, word: str) -> list[str]: ...
    def related(
        self,
        word: str,
        relation: str,
        pos: str | None = None,
        sense_index: int | None = None,
    ) -> list[str]: ...
    def expand_query(
        self, terms: list[str], relations: list[str], max_depth: int = 1
    ) -> list[str]: ...
    def expand_query_sense_aware(
        self,
        terms: list[tuple[str, str | None, int | None]],
        relations: list[str],
    ) -> list[str]: ...
    def get_senses(self, word: str) -> list[dict[str, Any]]: ...
    def save(self, path: str) -> None: ...
    def to_fst_set(self, include_inflections: bool = True) -> FstSet: ...
    def __len__(self) -> int: ...
    def __contains__(self, word: str) -> bool: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...
