"""Type stubs for kaos_nlp_core._rust.matching.

Match-returning entrypoints emit native pyclasses defined in
``kaos_nlp_core._rust.spans`` (``PyMatchSpan``, ``PyPatternMatchSpan``,
``PyRegexMatchSpan``, ``PyFstSearchResult``) — typed structurally
identical to the prior dict-shape but without the
Rust→PyDict→Python-dataclass round trip.
"""

from kaos_nlp_core._rust.spans import (
    PyFstSearchResult,
    PyMatchSpan,
    PyPatternMatchSpan,
    PyRegexMatchSpan,
)

class MultiPatternMatcher:
    def __init__(
        self,
        patterns: list[str],
        case_insensitive: bool = False,
        longest_match: bool = False,
    ) -> None: ...
    def find_all(self, haystack: str) -> list[PyPatternMatchSpan]: ...
    def find_all_batch(self, haystacks: list[str]) -> list[list[PyPatternMatchSpan]]: ...
    def is_match(self, haystack: str) -> bool: ...
    def count(self, haystack: str) -> int: ...
    def replace_all(self, haystack: str, replacements: list[str]) -> str: ...
    def pattern_count(self) -> int: ...
    def __getnewargs__(self) -> tuple[list[str], bool, bool]: ...

class RegexMatcher:
    def __init__(self, pattern: str) -> None: ...
    def find_all(self, haystack: str) -> list[PyRegexMatchSpan]: ...
    def find_all_batch(self, haystacks: list[str]) -> list[list[PyRegexMatchSpan]]: ...
    def find_first(self, haystack: str) -> PyRegexMatchSpan | None: ...
    def is_match(self, haystack: str) -> bool: ...
    def count(self, haystack: str) -> int: ...
    def replace_all(self, haystack: str, replacement: str) -> str: ...
    def split(self, haystack: str) -> list[str]: ...
    def pattern(self) -> str: ...
    def __getnewargs__(self) -> tuple[str]: ...

class RegexSetMatcher:
    def __init__(self, patterns: list[str]) -> None: ...
    def matching_patterns(self, haystack: str) -> list[int]: ...
    def is_match(self, haystack: str) -> bool: ...
    def pattern_count(self) -> int: ...
    def __getnewargs__(self) -> tuple[list[str]]: ...

class FstSet:
    def __init__(self, keys: list[str]) -> None: ...
    @staticmethod
    def load(path: str) -> FstSet: ...
    def save(self, path: str) -> None: ...
    def contains(self, key: str) -> bool: ...
    def fuzzy_search(self, query: str, max_distance: int) -> list[PyFstSearchResult]: ...
    def prefix_search(self, prefix: str) -> list[str]: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...
    def __getnewargs__(self) -> tuple[list[str]]: ...

class FstMap:
    def __init__(self, entries: list[tuple[str, int]]) -> None: ...
    def get(self, key: str) -> int | None: ...
    def contains_key(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...
    def __getnewargs__(self) -> tuple[list[tuple[str, int]]]: ...

def substring_find_all(haystack: str, needle: str) -> list[PyMatchSpan]: ...
def substring_find_all_batch(haystacks: list[str], needle: str) -> list[list[PyMatchSpan]]: ...
def substring_find_first(haystack: str, needle: str) -> PyMatchSpan | None: ...
def substring_count(haystack: str, needle: str) -> int: ...
def substring_count_batch(haystacks: list[str], needle: str) -> list[int]: ...
def substring_find_all_case_insensitive(haystack: str, needle: str) -> list[PyMatchSpan]: ...
