"""Type stubs for kaos_nlp_core._rust.segmentation."""

from typing import TypedDict

class SegmentResult(TypedDict):
    start: int
    end: int
    text: str
    confidence: float

class PunktParameters:
    def __init__(self) -> None: ...
    @staticmethod
    def load(path: str) -> PunktParameters: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def from_json(json: str) -> PunktParameters: ...
    def to_json(self) -> str: ...
    @property
    def num_abbreviations(self) -> int: ...
    @property
    def num_collocations(self) -> int: ...
    @property
    def num_sent_starters(self) -> int: ...
    @property
    def abbreviations(self) -> list[str]: ...
    @property
    def collocations(self) -> list[tuple[str, str]]: ...
    @property
    def sent_starters(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

class PunktTokenizer:
    def __init__(self, params: PunktParameters | None = None) -> None: ...
    def tokenize(self, text: str, precision_recall: float | None = None) -> list[str]: ...
    def tokenize_spans(
        self, text: str, precision_recall: float | None = None
    ) -> list[tuple[int, int]]: ...
    def tokenize_paragraphs(
        self, text: str, precision_recall: float | None = None
    ) -> list[list[str]]: ...
    def tokenize_paragraphs_flat(
        self, text: str, precision_recall: float | None = None
    ) -> list[str]: ...
    def set_precision_recall(self, balance: float) -> None: ...
    def count_sentences(self, text: str) -> int: ...
    def tokenize_batch(
        self, texts: list[str], precision_recall: float | None = None
    ) -> list[list[str]]: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

class PunktTrainer:
    def __init__(self) -> None: ...
    def train(self, text: str, verbose: bool = False) -> PunktParameters: ...
    def load_abbreviations_from_json(self, path: str) -> int: ...
    def add_abbreviations(self, abbreviations: list[str]) -> None: ...
    def train_incremental(self, text: str) -> None: ...
    def finalize_training(self, verbose: bool = False) -> PunktParameters: ...

def py_segment_lines(text: str) -> list[SegmentResult]: ...
def py_segment_sentences(
    text: str, tokenizer: PunktTokenizer | None = None
) -> list[SegmentResult]: ...
def py_segment_paragraphs(
    text: str, tokenizer: PunktTokenizer | None = None
) -> list[SegmentResult]: ...
def py_segment_paragraphs_simple(text: str) -> list[SegmentResult]: ...

class LineRecord:
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def stripped_start(self) -> int: ...
    @property
    def stripped_end(self) -> int: ...
    @property
    def term_len(self) -> int: ...
    @property
    def terminator(self) -> str: ...
    @property
    def indent_chars(self) -> int: ...
    @property
    def byte_len(self) -> int: ...
    @property
    def char_len(self) -> int: ...
    @property
    def token_count(self) -> int: ...
    @property
    def case_profile(self) -> str: ...
    @property
    def punct_profile(self) -> int: ...
    @property
    def blank(self) -> bool: ...
    @property
    def blank_before(self) -> bool: ...
    @property
    def blank_after(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

class NormalizedText:
    @property
    def text(self) -> str: ...
    @property
    def orig_char_offsets(self) -> list[int] | None: ...
    def original_char(self, char_offset: int) -> int | None: ...
    def __repr__(self) -> str: ...

class BoilerplateRun:
    @property
    def line_indices(self) -> list[int]: ...
    @property
    def canonical_text(self) -> str: ...
    @property
    def occurrences(self) -> int: ...
    @property
    def fingerprint(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def language_hint(self) -> str | None: ...
    def __repr__(self) -> str: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

class Enumerator:
    @property
    def kind(self) -> str: ...
    @property
    def value(self) -> int: ...
    @property
    def depth(self) -> int: ...
    @property
    def raw_start(self) -> int: ...
    @property
    def raw_end(self) -> int: ...
    @property
    def prefix_end(self) -> int: ...
    def segments(self) -> list[int]: ...
    def __repr__(self) -> str: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

def py_extract_line_records(text: str) -> list[LineRecord]: ...
def py_normalize(
    text: str,
    *,
    normalize_unicode_punct: bool = False,
    collapse_whitespace: bool = False,
    fold_case: bool = False,
    strip_punctuation: bool = False,
    strip_enumerator_prefix: bool = False,
) -> NormalizedText: ...
def py_detect_boilerplate(
    text: str,
    *,
    lines_per_page: int = 50,
    header_zone_lines: int = 3,
    footer_zone_lines: int = 3,
    min_occurrences: int = 3,
    min_rate: float = 0.5,
    skip_near_dup: bool = False,
    near_dup_threshold: float = 0.75,
    num_perm: int = 64,
    shingle_size: int = 4,
    zone_dominance: float = 0.7,
    drop_empty: bool = True,
) -> list[BoilerplateRun]: ...
def py_parse_enumerator(
    line: str,
    *,
    lexicon: str | None = None,
    custom_lexicon: list[tuple[str, str]] | None = None,
) -> Enumerator | None: ...
