"""Type stubs for kaos_nlp_core._rust.spans — typed result pyclasses.

These pyclasses replace the prior dict-shaped FFI boundary for hot per-result
emission paths (tokenizer, matchers, BM25). They are re-exported under their
unprefixed names from ``kaos_nlp_core.types`` so callers see the same shape
they did before (``from kaos_nlp_core.types import TokenSpan``).
"""

class PyTokenSpan:
    text: str
    start: int
    end: int
    def __init__(self, text: str, start: int, end: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[str, int, int]: ...

class PyMatchSpan:
    text: str
    start: int
    end: int
    def __init__(self, text: str, start: int, end: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[str, int, int]: ...

class PyPatternMatchSpan:
    text: str
    start: int
    end: int
    pattern_index: int
    def __init__(self, text: str, start: int, end: int, pattern_index: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[str, int, int, int]: ...

class PyRegexMatchSpan:
    text: str
    start: int
    end: int
    groups: list[str | None]
    def __init__(self, text: str, start: int, end: int, groups: list[str | None]) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getnewargs__(self) -> tuple[str, int, int, list[str | None]]: ...

class PyFstSearchResult:
    key: str
    distance: int
    def __init__(self, key: str, distance: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[str, int]: ...

class PyScoredDoc:
    doc_id: int
    score: float
    def __init__(self, doc_id: int, score: float) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[int, float]: ...

class PyPostingEntry:
    doc_id: int
    term_freq: int
    def __init__(self, doc_id: int, term_freq: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __getnewargs__(self) -> tuple[int, int]: ...

class PySegmentHit:
    text: str
    start: int
    end: int
    score: float
    def __init__(self, text: str, start: int, end: int, score: float) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getnewargs__(self) -> tuple[str, int, int, float]: ...
