"""Type stubs for kaos_nlp_core._rust.structures.

InvertedIndex query results emit native ``PyScoredDoc`` and
``PyPostingEntry`` pyclasses (audit perf finding #1 / P3).
"""

from kaos_nlp_core._rust.spans import PyPostingEntry, PyScoredDoc
from kaos_nlp_core._rust.tokenizer import Tokenizer

class SetVocabulary:
    def __init__(self, terms: list[str] | None = None) -> None: ...
    def insert(self, term: str) -> bool: ...
    def contains(self, term: str) -> bool: ...
    def remove(self, term: str) -> bool: ...
    def __len__(self) -> int: ...
    def __contains__(self, term: str) -> bool: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

class FrequencyVocabulary:
    def __init__(self) -> None: ...
    def insert(self, term: str) -> int: ...
    def insert_with_count(self, term: str, count: int) -> int: ...
    def contains(self, term: str) -> bool: ...
    def get_count(self, term: str) -> int | None: ...
    def get_id(self, term: str) -> int | None: ...
    def top_n(self, n: int) -> list[tuple[str, int]]: ...
    def total_count(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, term: str) -> bool: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

class IndexedVocabulary:
    def __init__(self) -> None: ...
    def insert(self, term: str) -> int: ...
    def get_id(self, term: str) -> int | None: ...
    def get_term(self, id: int) -> str | None: ...
    def contains(self, term: str) -> bool: ...
    def __len__(self) -> int: ...
    def __contains__(self, term: str) -> bool: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

class BloomVocabulary:
    def __init__(self, expected_items: int = 10000, false_positive_rate: float = 0.01) -> None: ...
    def insert(self, term: str) -> None: ...
    def contains(self, term: str) -> bool: ...
    def approx_len(self) -> int: ...
    def __contains__(self, term: str) -> bool: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

class InvertedIndex:
    def __init__(self) -> None: ...
    @staticmethod
    def load(path: str) -> InvertedIndex: ...
    def add(self, term: str, doc_id: int) -> None: ...
    def add_document(self, doc_id: int, terms: list[str]) -> None: ...
    def doc_freq(self, term: str) -> int: ...
    def idf(self, term: str) -> float: ...
    def tf_idf(self, term: str, doc_id: int) -> float: ...
    def tf_idf_weighted(
        self,
        term: str,
        doc_id: int,
        tf_weight: str = "raw",
        idf_weight: str = "standard",
    ) -> float: ...
    def score_tf_idf(
        self,
        terms: list[str],
        doc_id: int,
        tf_weight: str = "raw",
        idf_weight: str = "standard",
    ) -> float: ...
    def score_bm25(
        self,
        terms: list[str],
        doc_id: int,
        k1: float = 1.5,
        b: float = 0.75,
    ) -> float: ...
    def query_bm25(
        self,
        terms: list[str],
        top_k: int = 10,
        k1: float = 1.5,
        b: float = 0.75,
    ) -> list[PyScoredDoc]: ...
    def query_tf_idf(
        self,
        terms: list[str],
        top_k: int = 10,
        tf_weight: str = "sublinear",
        idf_weight: str = "smooth",
    ) -> list[PyScoredDoc]: ...
    def query_bm25_batch(
        self,
        queries: list[list[str]],
        top_k: int = 10,
        k1: float = 1.5,
        b: float = 0.75,
    ) -> list[list[PyScoredDoc]]: ...
    def query_tf_idf_batch(
        self,
        queries: list[list[str]],
        top_k: int = 10,
        tf_weight: str = "sublinear",
        idf_weight: str = "smooth",
    ) -> list[list[PyScoredDoc]]: ...
    def query_and(self, terms: list[str]) -> list[int]: ...
    def query_or(self, terms: list[str]) -> list[int]: ...
    @staticmethod
    def build_batch(documents: list[tuple[int, list[str]]]) -> InvertedIndex: ...
    @staticmethod
    def build_from_texts(
        doc_ids: list[int], texts: list[str], tokenizer: Tokenizer
    ) -> InvertedIndex: ...
    def term_count(self) -> int: ...
    def doc_count(self) -> int: ...
    def doc_length(self, doc_id: int) -> int: ...
    def avg_doc_length(self) -> float: ...
    def get_postings(self, term: str) -> list[PyPostingEntry] | None: ...
    def save(self, path: str) -> None: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

class SimilarityMatrix:
    @staticmethod
    def load(path: str) -> SimilarityMatrix: ...
    @staticmethod
    def from_sparse_vectors(
        features: list[list[tuple[int, float]]], metric: str = "cosine"
    ) -> SimilarityMatrix: ...
    def get_distance(self, i: int, j: int) -> float: ...
    def get_similarity(self, i: int, j: int) -> float: ...
    def k_nearest_neighbors(self, doc_idx: int, k: int) -> list[tuple[int, float]]: ...
    def n_docs(self) -> int: ...
    def mean_distance(self) -> float: ...
    def save(self, path: str) -> None: ...
    def __repr__(self) -> str: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

def _similarity_matrix_unpickle(state: bytes) -> SimilarityMatrix: ...

class SparseTermMatrix:
    def __init__(self) -> None: ...
    @staticmethod
    def load(path: str) -> SparseTermMatrix: ...
    def add_document(self, term_freqs: list[tuple[int, int]]) -> None: ...
    def get_term_freq(self, doc_id: int, term_id: int) -> int: ...
    def get_document_terms(self, doc_id: int) -> list[tuple[int, int]]: ...
    def document_term_count(self, doc_id: int) -> int: ...
    def document_length(self, doc_id: int) -> int: ...
    def cosine_similarity(self, doc_a: int, doc_b: int) -> float: ...
    def cosine_similarity_tfidf(self, doc_a: int, doc_b: int, doc_freqs: list[int]) -> float: ...
    def num_docs(self) -> int: ...
    def num_terms(self) -> int: ...
    def nnz(self) -> int: ...
    def density(self) -> float: ...
    def memory_usage(self) -> int: ...
    def save(self, path: str) -> None: ...
    def __repr__(self) -> str: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...

class LabeledSpan:
    def __init__(self, label: int, start: int, end: int, score: float = 1.0) -> None: ...
    @property
    def label(self) -> int: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def score(self) -> float: ...
    def __repr__(self) -> str: ...

class SpanIndex:
    def __init__(self) -> None: ...
    @staticmethod
    def from_tuples(
        spans: list[tuple[int, int, int, float | None]],
    ) -> SpanIndex: ...
    def add(self, label: int, start: int, end: int, score: float | None = None) -> int: ...
    def get(self, id: int) -> LabeledSpan | None: ...
    def containing(self, offset: int) -> list[int]: ...
    def overlapping(self, start: int, end: int) -> list[int]: ...
    def merge_adjacent(self, label: int, gap: int) -> None: ...
    def subtract(self, label_a: int, label_b: int) -> list[int]: ...
    def resolve_overlaps_by_score(self, label_set: list[int]) -> list[int]: ...
    def tombstone(self, id: int) -> bool: ...
    def freeze(self) -> None: ...
    def compact(self) -> list[int]: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> SpanIndex: ...
    def __len__(self) -> int: ...
    def __getstate__(self) -> bytes: ...
    def __setstate__(self, state: bytes) -> None: ...
