"""Type stubs for kaos_nlp_core._rust.structure."""

from typing import Any, TypedDict

class HeadingFeatureVector:
    @property
    def short_line(self) -> int: ...
    @property
    def blank_before(self) -> int: ...
    @property
    def blank_after(self) -> int: ...
    @property
    def indent_le_4(self) -> int: ...
    @property
    def case_allcaps(self) -> int: ...
    @property
    def case_titlecase(self) -> int: ...
    @property
    def case_initcap(self) -> int: ...
    @property
    def no_terminal_period(self) -> int: ...
    @property
    def colon_suffix(self) -> int: ...
    @property
    def inline_colon(self) -> int: ...
    @property
    def has_enumerator(self) -> int: ...
    @property
    def hierarchy_keyword(self) -> int: ...
    @property
    def lexical_heading(self) -> int: ...
    @property
    def table_row_shape(self) -> int: ...
    @property
    def column_gap_only(self) -> int: ...
    @property
    def definition_shape(self) -> int: ...
    @property
    def form_field_shape(self) -> int: ...
    @property
    def citation_density(self) -> float: ...
    @property
    def boilerplate(self) -> int: ...
    @property
    def long_prose(self) -> int: ...
    @property
    def score(self) -> float: ...
    @property
    def is_blank(self) -> int: ...
    @property
    def hierarchy_depth(self) -> int: ...
    @property
    def atx_depth(self) -> int: ...
    def heading_emit_cost(self) -> float: ...
    def __repr__(self) -> str: ...

class HeadingCandidate:
    @property
    def line_index(self) -> int: ...
    @property
    def score(self) -> float: ...
    @property
    def hierarchy_level(self) -> int: ...
    @property
    def numeric_depth(self) -> int: ...
    @property
    def enumerator_kind(self) -> str | None: ...
    @property
    def atx_depth(self) -> int: ...
    def picked_depth(self) -> int: ...
    def __repr__(self) -> str: ...

class _LabelLinesResult(TypedDict):
    labels: list[str]
    features: list[HeadingFeatureVector]
    candidates: list[HeadingCandidate]

def py_score_heading_features(
    text: str,
    *,
    enum_lexicon: str | None = None,
    custom_enum_lexicon: list[tuple[str, str]] | None = None,
    **scoring_kwargs: Any,
) -> list[HeadingFeatureVector]: ...
def py_decode_line_labels(
    text: str,
    *,
    enum_lexicon: str | None = None,
    custom_enum_lexicon: list[tuple[str, str]] | None = None,
    scoring: dict[str, Any] | None = None,
    decoder: dict[str, Any] | None = None,
) -> list[str]: ...
def py_label_lines(
    text: str,
    *,
    enum_lexicon: str | None = None,
    custom_enum_lexicon: list[tuple[str, str]] | None = None,
    scoring: dict[str, Any] | None = None,
    decoder: dict[str, Any] | None = None,
) -> _LabelLinesResult: ...
def py_citation_density(text: str) -> float: ...
