"""Type stubs for kaos_nlp_core._rust.tokenizer.

Tokenizer entrypoints emit native ``PyTokenSpan`` pyclasses (audit perf
finding #1 / P3) — same shape as the prior ``TokenResult`` TypedDict
but without the dict→dataclass round trip.
"""

from kaos_nlp_core._rust.spans import PyTokenSpan

class Tokenizer:
    def __init__(
        self,
        lowercase: bool = False,
        keep_punctuation: bool = False,
        prefix: int = 0,
        stopwords: list[str] | None = None,
        index: list[str] | None = None,
    ) -> None: ...
    def tokenize(self, text: str) -> list[PyTokenSpan]: ...
    def tokenize_words(self, text: str) -> list[str]: ...
    def tokenize_batch(self, texts: list[str]) -> list[list[PyTokenSpan]]: ...
    def tokenize_words_batch(self, texts: list[str]) -> list[list[str]]: ...
    def tokenize_regex(self, text: str, pattern: str | None = None) -> list[PyTokenSpan]: ...
    def tokenize_regex_words(self, text: str, pattern: str | None = None) -> list[str]: ...
    def tokenize_regex_batch(
        self, texts: list[str], pattern: str | None = None
    ) -> list[list[PyTokenSpan]]: ...
    def tokenize_regex_words_batch(
        self, texts: list[str], pattern: str | None = None
    ) -> list[list[str]]: ...
    def __getnewargs__(
        self,
    ) -> tuple[bool, bool, int, list[str] | None, list[str] | None]: ...

def tokenize(text: str, lowercase: bool = False, prefix: int = 0) -> list[PyTokenSpan]: ...
def tokenize_batch(
    texts: list[str], lowercase: bool = False, prefix: int = 0
) -> list[list[PyTokenSpan]]: ...
def tokenize_words(text: str, lowercase: bool = False, prefix: int = 0) -> list[str]: ...
def tokenize_words_batch(
    texts: list[str], lowercase: bool = False, prefix: int = 0
) -> list[list[str]]: ...
