"""Type stubs for kaos_nlp_core._rust.token_properties."""

from typing import TypedDict

class TokenPropertiesResult(TypedDict):
    is_letter_word: bool
    is_uppercase_word: bool
    is_lowercase_word: bool
    is_mixed_case_word: bool
    is_title_case_word: bool
    is_numeric_word: bool
    is_alphanumeric_word: bool
    starts_with_digit: bool
    has_punctuation: bool
    has_dash: bool
    is_hyphenated: bool
    is_abbreviation: bool
    has_emoji: bool
    is_symbolic_word: bool
    ends_with_terminal: bool

def classify_token(token: str) -> TokenPropertiesResult: ...
def classify_tokens(tokens: list[str]) -> list[TokenPropertiesResult]: ...
def is_letter_word(token: str) -> bool: ...
def is_uppercase_word(token: str) -> bool: ...
def is_lowercase_word(token: str) -> bool: ...
def is_title_case_word(token: str) -> bool: ...
def is_numeric_word(token: str) -> bool: ...
def is_alphanumeric_word(token: str) -> bool: ...
def is_abbreviation(token: str) -> bool: ...
def has_emoji(token: str) -> bool: ...
